### ISSUE TITLE
Continous Delivery application to K8S Cluster with GitLab CI

### ISSUE THREAD

**Issue by haminhcong** [haminhcong/k8s-til#18]
Two methods

## Method 1 - kubectl

- Patch manifest image version then using `kubectl apply` manifest to cluster
- Or using `helm upgrade` deploy new app chart version
- Or update application config repository, then using ArgoCD sync config to target k8s cluster

common solutions

```yaml
stages:
  - build
  - deploy

build:
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://localhost:2375/
  image: cr.yandex/yc/metadata-token-docker-helper:0.2
  services:
    - docker:19.03.1-dind
  script:
    - docker build . -t cr.yandex/<registry ID>/hello:gitlab-$CI_COMMIT_SHORT_SHA
    - docker push cr.yandex/<registry ID>/hello:gitlab-$CI_COMMIT_SHORT_SHA

deploy:
  image: gcr.io/cloud-builders/kubectl:latest
  stage: deploy
  script:
    - kubectl config set-cluster k8s --server="$KUBE_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials admin --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster=k8s --user=admin
    - kubectl config use-context default
    - sed -i "s/__VERSION__/gitlab-$CI_COMMIT_SHORT_SHA/" k8s.yaml
    - kubectl apply -f k8s.yaml
```

```yaml
stages:
  - deploy

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2
  APP_NAME: my-first-app

deploy:
  stage: deploy
  image: alpine/helm:3.2.1
  script:
    - helm upgrade ${APP_NAME} ./charts --install --values=./charts/values.yaml --namespace ${APP_NAME}
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: always
```

```yaml
# https://www.arctiq.ca/our-blog/2021/1/18/cicd-pipelines-using-gitlab-ci-argo-cd-with-anthos-config-management/
deploy_dev:
  stage: deploy_prod
  environment:
    name: dev
  image: daniyalj/alpine-envsub:v1
  before_script:
     - git config --global user.email "gitlab@gitlab.com"
     - git config --global user.name "Mr GitLab"
     - mkdir -p ~/.ssh
     - echo "$GIT_SSH_PRIV_KEY" > ~/.ssh/id_rsa
     - chmod 400 ~/.ssh/id_rsa
     - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  script:
    - git clone -b ${ENV_BRANCH} git@gitlab.com:daniyalj/${ENV_GIT_REPO}.git
    - cd ${ENV_GIT_REPO}
    - git checkout -b ${CI_ENVIRONMENT_NAME}-${CI_PIPELINE_ID}
    - envsubst < pipeline-staging/spring-store.yaml > config-management/namespaces/argocd/spring-store-app-${CI_ENVIRONMENT_NAME}.yaml
    - git add . && git commit -m "deploy ${CI_ENVIRONMENT_NAME}-${CI_PIPELINE_ID}" && git push -o merge_request.label="Deploy" -o merge_request.create -o merge_request.target=${ENV_BRANCH} --force origin ${CI_ENVIRONMENT_NAME}-${CI_PIPELINE_ID}
  only:
  - master
```

## Method 2 - GitLab Kubernetes Agent

- https://docs.gitlab.com/ee/user/clusters/agent/

## References

- https://cloud.yandex.com/en/docs/solutions/infrastructure-management/gitlab-containers
- https://piotrminkowski.com/2020/10/19/gitlab-ci-cd-on-kubernetes/
- https://gitlab.com/jacobmammoliti/random-app/-/blob/master/.gitlab-ci.yml
- https://www.padok.fr/en/blog/kubernetes-gitlab-pipeline
- https://about.gitlab.com/blog/2016/12/14/continuous-delivery-of-a-spring-boot-application-with-gitlab-ci-and-kubernetes/
- https://nextlinklabs.com/insights/kubernetes-ci-cd-gitlab-with-helm
- https://www.arctiq.ca/our-blog/2021/1/18/cicd-pipelines-using-gitlab-ci-argo-cd-with-anthos-config-management/
